Repository sofarsounds/maestro, pull requests merged in 2019-06, with the labels that each got.

#5 Add basic usage docs + fix storybook logo
  README.md
  package.json
  packages/stories/.storybook/sofarTheme.js
  packages/stories/package.json
Labels: chore, documentation

#6 Change github pages automatic deployment author
  bin/deploy-gh-pages.sh
Labels: chore

#19 Pagination
  packages/stories/src/atoms/atoms.stories.tsx
  packages/stories/src/molecules/molecules.stories.tsx
  packages/uikit/package.json
  packages/uikit/src/atoms/Badge/Badge.test.tsx
  packages/uikit/src/atoms/Badge/__snapshots__/Badge.test.tsx.snap
  packages/uikit/src/atoms/Badge/index.tsx
  packages/uikit/src/atoms/Button/__snapshots__/Button.test.tsx.snap
  packages/uikit/src/atoms/Container/__snapshots__/Container.test.tsx.snap
  packages/uikit/src/atoms/FormElements/__snapshots__/FormElements.test.tsx.snap
  packages/uikit/src/atoms/Grid/__snapshots__/Grid.test.tsx.snap
  packages/uikit/src/atoms/Icon/registry.ts
  packages/uikit/src/atoms/Typography/__snapshots__/Typography.test.tsx.snap
  packages/uikit/src/index.tsx
  packages/uikit/src/molecules/Pagination/Arrow.test.tsx
  packages/uikit/src/molecules/Pagination/Arrow.tsx
  packages/uikit/src/molecules/Pagination/Compact.test.tsx
  packages/uikit/src/molecules/Pagination/Compact.tsx
  packages/uikit/src/molecules/Pagination/Ellipsis.test.tsx
  packages/uikit/src/molecules/Pagination/Ellipsis.tsx
  packages/uikit/src/molecules/Pagination/PageBubble.test.tsx
  packages/uikit/src/molecules/Pagination/PageBubble.tsx
  packages/uikit/src/molecules/Pagination/Pages.test.tsx
  packages/uikit/src/molecules/Pagination/Pages.tsx
  packages/uikit/src/molecules/Pagination/Pagination.test.tsx
  packages/uikit/src/molecules/Pagination/__snapshots__/Arrow.test.tsx.snap
  packages/uikit/src/molecules/Pagination/__snapshots__/Compact.test.tsx.snap
  packages/uikit/src/molecules/Pagination/__snapshots__/Ellipsis.test.tsx.snap
  packages/uikit/src/molecules/Pagination/__snapshots__/PageBubble.test.tsx.snap
  packages/uikit/src/molecules/Pagination/__snapshots__/Pages.test.tsx.snap
  packages/uikit/src/molecules/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/uikit/src/molecules/Pagination/index.tsx
  packages/uikit/src/theme/index.ts
  packages/uikit/src/typings/theme.ts
  tsconfig.json
Labels: enhancement
